[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bindgen = "0.71"
env_logger = "0.10"
log = "0.4"
cmake = "0.1.52"
fs_extra = "1.3"
embuild = "0.33"
directories = "4"
tempdir = "0.3"
clap = { version = "4.4", features = ["derive"] }
