name: Continuous Integration

on:
  push:
    paths-ignore:
      - "**/README.md"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Enable caching
        uses: Swatinem/rust-cache@v2
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          target: riscv32imac-unknown-none-elf
          toolchain: nightly
          components: rust-src
      - name: Fmt
        run: cd openthread; cargo fmt --all -- --check --color always
      - name: Clippy
        run: cd openthread; cargo clippy --all-targets --all-features --workspace -- -D warnings
      - name: Build
        run: cd openthread; cargo build
