name: Continuous Integration

on:
  push:
    paths-ignore:
      - "**/README.md"
  pull_request:
  workflow_dispatch:

env:
  rust_toolchain: nightly
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - default
    steps:
      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.rust_toolchain }}
          components: rustfmt, clippy, rust-src

      - name: Setup | Rust thumbv6m-none-eabi
        run: rustup target add thumbv6m-none-eabi

      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Build | Fmt Check
        run: cd openthread; cargo fmt -- --check

      - name: Build | Clippy
        run: cd openthread; cargo clippy --no-deps -- -Dwarnings

      - name: Build | Compile
        run: cd openthread; cargo build

      - name: Examples-ESP-Build | Fmt Check
        run: cd examples/esp; cargo fmt -- --check

      - name: Examples-ESP-Build | Clippy
        run: cd examples/esp; cargo clippy --no-deps -- -Dwarnings

      - name: Examples-ESP-Build | Compile
        run: cd examples/esp; cargo build
